"use client";

import * as React from "react";
import * as AccordionPrimitive from "@radix-ui/react-accordion";
import { Plus, Minus, ArrowRight } from "lucide-react";

const faqItems = [
{
  value: "faq-1",
  question: "Is Merus free to try?",
  answer: "Yes, Merus offers a free plan that allows you to explore its core features. You can get started right away without needing a credit card."
},
{
  value: "faq-2",
  question: "Will this affect my ability to conduct independent research?",
  answer: "Not at all. Merus is designed to be a research assistant, augmenting your skills, not replacing them. It handles tedious tasks, freeing you up to focus on critical thinking, analysis, and drawing unique insights, ensuring you remain in full control of your research process."
},
{
  value: "faq-3",
  question: "How can I verify the accuracy of AI-generated responses?",
  answer: "Every piece of information and every insight generated by Merus is directly linked to the original source material. You can click on the in-line citations to instantly verify the context and accuracy of any response against the source document."
},
{
  value: "faq-4",
  question: "How secure is my data with Merus?",
  answer: "We take data security very seriously. Merus is built with enterprise-grade security standards, is SOC 2 and ISO27001 compliant, and all your data is encrypted both in transit and at rest. You can also delete your data at any time."
},
{
  value: "faq-5",
  question: "What file types does Merus support?",
  answer: "Merus supports a wide range of file types common in academic and professional research, including PDF, DOCX, TXT, and PPTX. You can upload individual files or entire folders to build your research library."
},
{
  value: "faq-6",
  question: "What is your refund policy?",
  answer: "We offer a straightforward refund policy for our premium plans. If you are not satisfied with our service, you can request a full refund within a specified period from your purchase date, as detailed in our terms of service."
}];


const FaqSection = () => {
  return (
    <section className="text-foreground w-full py-24 md:py-32 !bg-white">
      <div className="mx-auto max-w-[1280px] px-9 md:px-13 lg:px-16">
        <div className="grid grid-cols-1 lg:grid-cols-2 items-start gap-16 lg:gap-24">
          <div className="lg:sticky lg:top-32">
            <h2 className="text-[48px] leading-tight tracking-tight !font-(family-name:--font-playfair-display) !font-normal">
              Frequently Asked Questions
            </h2>
          </div>
          <div>
            <AccordionPrimitive.Root
              type="single"
              collapsible
              className="w-full">

              {faqItems.map((faq, index) =>
              <AccordionPrimitive.Item
                key={faq.value}
                value={faq.value}
                className="border-b border-border">

                  <AccordionPrimitive.Header className="flex">
                    <AccordionPrimitive.Trigger className="group flex w-full flex-1 items-center justify-between py-6 text-left text-lg font-medium transition-all hover:no-underline">
                      <span className="!whitespace-pre-line">{faq.question}</span>
                      <div className="relative h-5 w-5">
                        <Plus className="h-5 w-5 shrink-0 transform-gpu transition-all duration-300 group-data-[state=open]:rotate-90 group-data-[state=open]:opacity-0" />
                        <Minus className="absolute inset-0 h-5 w-5 shrink-0 transform-gpu opacity-0 transition-all duration-300 group-data-[state=open]:rotate-0 group-data-[state=open]:opacity-100" />
                      </div>
                    </AccordionPrimitive.Trigger>
                  </AccordionPrimitive.Header>
                  <AccordionPrimitive.Content className="overflow-hidden text-base text-secondary-foreground transition-all data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down">
                    <div className="pb-6 pt-0 leading-relaxed !whitespace-pre-line">
                      {faq.answer}
                    </div>
                  </AccordionPrimitive.Content>
                </AccordionPrimitive.Item>
              )}
            </AccordionPrimitive.Root>
            <a
              href="https://anara.com/faqs"
              className="group mt-10 inline-flex items-center gap-2 text-sm font-medium text-secondary-foreground transition-colors hover:text-foreground">

              More FAQs
              <ArrowRight className="h-4 w-4 transition-transform duration-200 group-hover:translate-x-1" />
            </a>
          </div>
        </div>
      </div>
    </section>);

};

export default FaqSection;